name = "DiscStochSim"
uuid = "768643f0-4499-4e3e-a9fb-cd287868bfc9"
authors = ["Aditya Dendukuri"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
